import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

class PDFReportGenerator:
    """PDF Report Generator for offline agricultural report rendering."""

    @staticmethod
    def generate_pdf(output_path, title, report_type, data_dict):
        """Generate a styled PDF document locally."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        doc = SimpleDocTemplate(output_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#1b4332'),
            alignment=1, # Center
            spaceAfter=15
        )

        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#2d6a4f'),
            alignment=1,
            spaceAfter=20
        )

        heading2_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#2d6a4f'),
            spaceBefore=15,
            spaceAfter=8
        )

        body_style = styles['BodyText']

        # Title Block
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(f"Smart Farmer Assistant — {report_type} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", subtitle_style))
        story.append(Spacer(1, 10))

        # Data Table
        table_data = [["Attribute / Field", "Value / Details"]]
        for k, v in data_dict.items():
            key_str = str(k).replace('_', ' ').title()
            val_str = str(v)
            table_data.append([Paragraph(f"<b>{key_str}</b>", body_style), Paragraph(val_str, body_style)])

        t = Table(table_data, colWidths=[200, 340])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#2d6a4f')),
            ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d8f3dc')),
        ]))

        story.append(t)
        story.append(Spacer(1, 20))

        # Footer Notice
        story.append(Paragraph("<i>This document was locally generated by Smart Farmer Assistant AI Platform. No internet connectivity required.</i>", styles['Italic']))

        doc.build(story)
        return output_path
